## 子主题3绘图

In [32]:
from plotnine import *
import pandas as pd

In [33]:
data_path = "../../Datasets/subtopic3/subtopic3.csv"
data = pd.read_csv(data_path).convert_dtypes()
data = data.dropna()
data["dream_type"] = data["positive_or_not"].map({
    1: "positive_dream",
    0: "negative_dream",
})
data.head(3)

,dream_id,positive_or_not,cluster_coeff,avg_min_path,feedback_loops,gini_coeff,dream_type
0,izzy16_592,1,0.361111,1.8,1,0.25,positive_dream
1,izzy16_593,1,0.0,2.333333,0,0.133333,positive_dream
2,izzy16_594,1,0.0,2.333333,1,0.25,positive_dream

In [34]:
def MyBoxPlot(y_axis):
    p = (
        ggplot(data, aes(x="dream_type", y=y_axis))
        + geom_boxplot()
        + labs(x="dream type", y=y_axis, title=y_axis+" boxplot")
    ) 
    return p

In [35]:
# plot 箱线图

p_gini = MyBoxPlot("gini_coeff")
p_gini.save("gini_coeff_box_plot.jpg")

p_cluster = MyBoxPlot("cluster_coeff")
p_cluster.save("cluster_coeff_box_plot.jpg")

# avg_min_path: 限制y轴范围 (0, 10)，99%分位数在9.77
p_avg = (
    ggplot(data, aes(x="dream_type", y="avg_min_path"))
    + geom_boxplot()
    + scale_y_continuous(limits=(0, 10))
    + labs(x="dream type", y="avg_min_path", title="avg_min_path boxplot")
)
p_avg.save("avg_min_path_box_plot.jpg")

# feedback_loops: 限制y轴范围 (0, 50)，99%分位数在47
p_feed = (
    ggplot(data, aes(x="dream_type", y="feedback_loops"))
    + geom_boxplot()
    + scale_y_continuous(limits=(0, 50))
    + labs(x="dream type", y="feedback_loops", title="feedback_loops boxplot")
)
p_feed.save("feedback_loops_box_plot.jpg")

/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: gini_coeff_box_plot.jpg
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: cluster_coeff_box_plot.jpg
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: avg_min_path_box_plot.jpg
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/layer.py:293: PlotnineWarning: stat_boxplot : Removed 243 rows containing non-finite values.
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:623: PlotnineWarning: Saving 6.4 x 4.8 in image.
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/ggplot.py:624: PlotnineWarning: Filename: feedback_loops_box_plot.jpg
/opt/homebrew/Caskroom/miniconda/base/envs/statistic/lib/python3.10/site-packages/plotnine/layer.py:293: PlotnineWarning: stat_boxplot : Removed 249 rows containing non-finite values.

In [39]:
# 数值指标对比表
metrics = ['cluster_coeff', 'feedback_loops', 'gini_coeff']
summary = data.groupby('dream_type')[metrics].agg(['mean', 'median', 'std']).round(4)
summary.to_csv("compare_table.csv", index=False, encoding="utf-8")
summary

               cluster_coeff                feedback_loops                   \
                        mean median     std           mean median       std
dream_type
negative_dream         0.099    0.0  0.1543         8.3817    3.0  192.7977
positive_dream        0.0849    0.0   0.156         4.4288    2.0   75.6527

               gini_coeff
                     mean  median     std
dream_type
negative_dream     0.1766  0.1714  0.0727
positive_dream     0.1642  0.1667  0.0743